workflow:
    name: impala

R:
  image: rstudio/r-base:4.4.3-noble
  script:
    - export http_proxy=http://proxy.sandia.gov:80
    - export https_proxy=http://proxy.sandia.gov:80
    - export _R_CHECK_FORCE_SUGGESTS_=0
    - wget --no-proxy https://cee-gitlab.sandia.gov/-/snippets/225/raw/master/install_certs.sh -O - | bash -
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y -f libssl-dev libfontconfig1-dev
    - R -e 'install.packages(c("BASS", "progress", "einsum", "fdasrvf", "devtools"),repos = "http://cran.us.r-project.org")'
    - R -e 'devtools::install_github("gqcollins/BayesPPR",repos = "http://cran.us.r-project.org")'
    - R -e 'devtools::install_git('https://cee-gitlab.sandia.gov/statistics/mvBayes.git', subdir='mvBayesR',repos = "http://cran.us.r-project.org")"'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual

